ExUnit.start()
Code.require_file("support/snapshot_support.exs", __DIR__)
Code.require_file("support/test_support.exs", __DIR__)
Code.require_file("support/agent_profile_fixture.exs", __DIR__)
SymphonyElixir.TestAgentProfileFixture.install!()
