defmodule SymphonyElixir.MixProject do
  use Mix.Project

  def project do
    [
      app: :symphony_elixir,
      version: "0.1.0",
      elixir: "~> 1.19",
      compilers: [:phoenix_live_view] ++ Mix.compilers(),
      start_permanent: Mix.env() == :prod,
      # Coverage policy (EMB-1180): `make all` enforces a documented,
      # non-perfect aggregate floor over the full production denominator.
      # Perfect coverage of every hand-written module is explicitly not a
      # pass condition, and no module is excluded to protect the number.
      # The only permitted exclusions are compiler/framework-generated
      # modules with no repository-authored executable behavior, each named
      # and justified below. The floor may rise when real coverage rises; it
      # must never be met by shrinking this denominator, filtering warnings,
      # or adding meaningless line-touch tests. Measured aggregate at policy
      # adoption: ~82% over all repository-owned modules.
      test_coverage: [
        summary: [
          threshold: 80
        ],
        ignore_modules: [
          # Generated by the Phoenix router macro; contains no
          # repository-authored code.
          SymphonyElixirWeb.Router.Helpers
        ]
      ],
      test_ignore_filters: [
        "test/support/snapshot_support.exs",
        "test/support/claude_shim_fixture.exs",
        "test/support/test_support.exs",
        "test/support/agent_profile_fixture.exs",
        "test/support/non_live_linear_client.exs",
        "test/support/linear_traffic_sentinel.exs"
      ],
      dialyzer: [
        plt_add_apps: [:mix]
      ],
      escript: escript(),
      aliases: aliases(),
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      mod: {SymphonyElixir.Application, []},
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:bandit, "~> 1.8"},
      {:floki, ">= 0.30.0", only: :test},
      {:lazy_html, ">= 0.1.0", only: :test},
      {:phoenix, "~> 1.8.0"},
      {:phoenix_html, "~> 4.2"},
      {:phoenix_live_view, "~> 1.1.0"},
      {:req, "~> 0.5"},
      {:jason, "~> 1.4"},
      {:toml, "~> 0.7.0"},
      {:yaml_elixir, "~> 2.12"},
      {:solid, "~> 1.2"},
      {:ecto, "~> 3.13"},
      {:credo, "~> 1.7", only: [:dev, :test], runtime: false},
      {:dialyxir, "~> 1.4", only: [:dev], runtime: false}
    ]
  end

  defp aliases do
    [
      setup: ["deps.get"],
      build: ["escript.build"],
      lint: ["specs.check", "credo --strict"],
      # Non-live gate boot seal (EMB-1180): the application must never
      # auto-start before test_helper.exs has sealed the Linear client
      # module and pinned a non-repo workflow file, so every `mix test`
      # entrypoint (including `mix test --cover`) starts the app itself.
      test: ["test --no-start"]
    ]
  end

  defp escript do
    [
      app: nil,
      main_module: SymphonyElixir.CLI,
      name: "symphony",
      path: "bin/symphony"
    ]
  end
end
